name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

defaults:
  run:
    shell: bash

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies (linux)
      run: |
        sudo apt-get update
        sudo apt-get install xorg-dev libglu1-mesa-dev
      if: matrix.os == 'ubuntu-latest'
    - name: Install dependencies (windows)
      run: |
        git clone https://github.com/PistonDevelopers/binaries
        mv binaries/x86_64/freetype.dll $HOME/.rustup/toolchains/stable-x86_64-pc-windows-msvc/lib/rustlib/x86_64-pc-windows-msvc/lib/
        mv binaries/x86_64/freetype.lib $HOME/.rustup/toolchains/stable-x86_64-pc-windows-msvc/lib/rustlib/x86_64-pc-windows-msvc/lib/
      if: matrix.os == 'windows-latest'

    - run: cargo fmt -- --check
    - run: cargo build --verbose
    - run: cargo test --verbose
